version: '3.9'

networks:
  laravel:
      driver: bridge

services:

  mysql:
    image: mysql:5.7.35
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

